# Generated by Django 5.0.1 on 2024-02-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list)),
                ('servicesImage', models.ImageField(upload_to='services_images/')),
            ],
        ),
    ]
